--------------------------------------------------------
--  File created - dinsdag-september-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WATSON_CERTIFICATE_PARTS_1
--------------------------------------------------------

  CREATE TABLE "INTERSPC"."WATSON_CERTIFICATE_PARTS_1" 
   (	"PRT_WTS_DOCKEY" VARCHAR2(50 CHAR), 
	"PRT_NO" VARCHAR2(30 CHAR), 
	"PRT_PRODUCTLINE" VARCHAR2(50 CHAR), 
	"PRT_SIDEWALL_PLATES" VARCHAR2(20 CHAR), 
	"PRT_CURRENT_VALIDITY" VARCHAR2(20 CHAR), 
	"PRT_WEEK_VALIDITY" VARCHAR2(20 CHAR), 
	"PRT_SIDEWALL_MARKING" VARCHAR2(20 CHAR), 
	"PRT_TYRE_STICKER" VARCHAR2(1 CHAR), 
	"PRT_REMARKS" VARCHAR2(100 CHAR), 
	"PRT_STATUS" VARCHAR2(20 CHAR), 
	"PRT_SECTION_REF_ID" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WTS_PRT_PK_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "INTERSPC"."WTS_PRT_PK_1" ON "INTERSPC"."WATSON_CERTIFICATE_PARTS_1" ("PRT_WTS_DOCKEY", "PRT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table WATSON_CERTIFICATE_PARTS_1
--------------------------------------------------------

  ALTER TABLE "INTERSPC"."WATSON_CERTIFICATE_PARTS_1" ADD CONSTRAINT "WTS_PRT_PK_1" PRIMARY KEY ("PRT_WTS_DOCKEY", "PRT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INTERSPC"."WATSON_CERTIFICATE_PARTS_1" MODIFY ("PRT_NO" NOT NULL ENABLE);
  ALTER TABLE "INTERSPC"."WATSON_CERTIFICATE_PARTS_1" MODIFY ("PRT_WTS_DOCKEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table WATSON_CERTIFICATE_PARTS_1
--------------------------------------------------------

  ALTER TABLE "INTERSPC"."WATSON_CERTIFICATE_PARTS_1" ADD CONSTRAINT "WTS_PRT_WTS_FK_1" FOREIGN KEY ("PRT_WTS_DOCKEY")
	  REFERENCES "INTERSPC"."WATSON_CERTIFICATES_1" ("WTS_DOCKEY") ENABLE;
