--------------------------------------------------------
--  File created - dinsdag-september-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WATSON_CERTIFICATES
--------------------------------------------------------

  CREATE TABLE "INTERSPC"."WATSON_CERTIFICATES" 
   (	"CRT_PATH" VARCHAR2(91 BYTE), 
	"CRT_FOLDER_NAME" VARCHAR2(38 BYTE), 
	"CRT_DOCKEY" VARCHAR2(34 BYTE), 
	"CRT_SUBJECT" VARCHAR2(100 BYTE), 
	"CRT_CERTIFICATE" VARCHAR2(20 BYTE), 
	"CRT_CERTIFICATE_CODE" VARCHAR2(60 BYTE), 
	"CRT_CERTIFICATE_TYPE" VARCHAR2(7 BYTE), 
	"CRT_PRODUCTSIZE" VARCHAR2(60 BYTE), 
	"CRT_PRODUCTFAMILY" VARCHAR2(29 BYTE), 
	"CRT_PRODUCT_CODE" VARCHAR2(60 BYTE), 
	"CRT_ATTACHMENTS" VARCHAR2(73 BYTE), 
	"CRT_STATUS" VARCHAR2(8 BYTE), 
	"CRT_VERSION" VARCHAR2(3 BYTE), 
	"CRT_AUTHOR" VARCHAR2(26 BYTE), 
	"CRT_BRAND" VARCHAR2(59 BYTE), 
	"CRT_ISSUE_DATE" VARCHAR2(8 BYTE), 
	"CRT_WATSON_UID" VARCHAR2(32 BYTE), 
	"CRT_TEXT" VARCHAR2(50 BYTE), 
	"CRT_FILE" BLOB, 
	"CRT_WATSON_LABEL_UID" VARCHAR2(32 BYTE), 
	"CRT_TYPE" VARCHAR2(30 BYTE), 
	"CRT_SECTION_WIDTH" VARCHAR2(10 BYTE), 
	"CRT_ASPECT_RATIO" VARCHAR2(100 BYTE), 
	"CRT_RIM_SIZE" VARCHAR2(10 BYTE), 
	"CRT_LOAD_INDEX" VARCHAR2(10 BYTE), 
	"CRT_SPEED_INDEX" VARCHAR2(10 BYTE), 
	"CRT_PRODUCT_LINE" VARCHAR2(40 BYTE), 
	"CRT_OBJECT_ID" NUMBER(8,0), 
	"CRT_LABEL_OBJECT_ID" NUMBER(8,0), 
	"CRT_REVISION" NUMBER(8,0), 
	"CRT_SIDEWALL_PLATES" VARCHAR2(20 BYTE), 
	"CRT_CURRENT_VALIDITY" VARCHAR2(20 BYTE), 
	"CRT_WEEK_VALIDITY" VARCHAR2(20 BYTE), 
	"CRT_SIDEWALL_MARKING" VARCHAR2(20 BYTE), 
	"CRT_TYRE_STICKER" VARCHAR2(3 BYTE), 
	"CRT_REMARKS" VARCHAR2(100 BYTE), 
	"CRT_ACTION" VARCHAR2(10 BYTE), 
	"CRT_DESCRIPTION" VARCHAR2(50 BYTE), 
	"CRT_PROPERTY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CRT_FILE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index WTS_CRT_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INTERSPC"."WTS_CRT_UK" ON "INTERSPC"."WATSON_CERTIFICATES" ("CRT_WATSON_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WTS_CRT_IDX
--------------------------------------------------------

  CREATE INDEX "INTERSPC"."WTS_CRT_IDX" ON "INTERSPC"."WATSON_CERTIFICATES" ("CRT_CERTIFICATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table WATSON_CERTIFICATES
--------------------------------------------------------

  ALTER TABLE "INTERSPC"."WATSON_CERTIFICATES" ADD CONSTRAINT "WTS_CRT_UK" UNIQUE ("CRT_WATSON_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WATSON_CERTIFICATES
--------------------------------------------------------

  ALTER TABLE "INTERSPC"."WATSON_CERTIFICATES" ADD CONSTRAINT "WTS_CRT_CRT_FK" FOREIGN KEY ("CRT_WATSON_LABEL_UID")
	  REFERENCES "INTERSPC"."WATSON_CERTIFICATES" ("CRT_WATSON_UID") ENABLE;
