begin
execute immediate 'CREATE TABLE ITNUTRESULTREMARK
(BOM_EXP_NO    		Number(8)    NOT NULL,
MOP_SEQUENCE_NO     Number(8)    DEFAULT 1,
ROW_ID         		Number(8)    NOT NULL,
COL_ID         		Number(8)    NOT NULL,
REMARK         		CLOB,
   CONSTRAINT xPK_ITNUTRESULTREMARK
   PRIMARY KEY ( BOM_EXP_NO, ROW_ID, COL_ID ) 
      USING INDEX 
      TABLESPACE SPECI PCTFREE 10
)
   TABLESPACE SPECD
   PCTFREE 10';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
