--*****************************************************************************************************
--*****************************************************************************************************
--*****************************************************************************************************
-- let op: ONDERSTAANDE ZAKEN ALLEEN UITVOEREN INDIEN DE CONFIG-TABEL OOK DAADWERKELIJK GEVULD IS ....
--*****************************************************************************************************
--*****************************************************************************************************
--*****************************************************************************************************
--*****************************************************************************************************

--
-- UPDATE-PK-EXISTS

--INTERSPEC
-- PK=J
UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_PK_EXISTS_JN = 'J' WHERE ASL_TABLE_NAME in (SELECT con.TABLE_NAME FROM ALL_CONSTRAINTS con WHERE OWNER='INTERSPC' AND  CONSTRAINT_TYPE='P') AND ASL_PK_EXISTS_JN IS NULL;
-- PK=N
UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_PK_EXISTS_JN = 'N' WHERE ASL_TABLE_NAME NOT in (SELECT con.TABLE_NAME FROM ALL_CONSTRAINTS con WHERE OWNER='INTERSPC' AND  CONSTRAINT_TYPE='P') AND ASL_PK_EXISTS_JN IS NULL;

--CONTROLE ACHTERAF
select count(*), asl_pk_exists_jn
from dba_aws_supplemental_log
group by asl_pk_exists_jn
order by asl_pk_exists_jn
;
/*
unilab:
157	J
24	N
--
interspec:
82	J
6	N
*/
--
COMMIT;

--
-- UPDATE ALS_SUPPL_LOG_TYPE
-- DEFAULT LOG-TYPE=ALL
update dba_aws_supplemental_log set ASL_SUPPL_LOG_TYPE = 'ALL' WHERE ASL_SUPPL_LOG_TYPE IS NULL;
/*
-- EVT. SPECIFIEK MAKEN PER EXISTING-PK. DOEN WIJ NU ECHTER NIET. WE LATEN ALLE TABELLEN OP "ALL" STAAN...-- EVT. SPECIFIEK MAKEN PER EXISTING-PK:
update dba_aws_supplemental_log set ASL_SUPPL_LOG_TYPE = CASE WHEN ASL_PK_EXISTS_JN = 'J' THEN 'PK' 
                                                              WHEN ASL_PK_EXISTS_JN = 'N' THEN 'ALL' 
															  ELSE '' END;
*/
select count(*), ASL_SUPPL_LOG_TYPE
from dba_aws_supplemental_log
group by ASL_SUPPL_LOG_TYPE
order by ASL_SUPPL_LOG_TYPE
;
commit;



--
-- ZET ALLE TABELLEN OP ACTIVE !
--
update dba_aws_supplemental_log set ASL_IND_ACTIVE_JN = 'J' WHERE ASL_IND_ACTIVE_JN IS NULL;
--
select count(*), asl_ind_active_jn
from dba_aws_supplemental_log
group by asl_ind_active_jn
order by asl_ind_active_jn
;
COMMIT;


--**************************************************************************************************
--ALLE TABELLEN MET EEN BLOB-COLUMN zetten we vooralsnog op INACTIVE. REPLICEREN GAAT NOG NIET GOED.
--**************************************************************************************************
SELECT COUNT(*), ASL_IND_ACTIVE_JN FROM DBA_AWS_SUPPLEMENTAL_LOG GROUP BY ASL_IND_ACTIVE_JN;

UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_IND_ACTIVE_JN  = 'N', ASL_OPMERKING=ASL_OPMERKING||' COLUMN=TEXT=CLOB' WHERE ASL_SCHEMA_OWNER = 'INTERSPC' AND  ASL_TABLE_NAME = 'FRAME_TEXT';
UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_IND_ACTIVE_JN  = 'N', ASL_OPMERKING=ASL_OPMERKING||' COLUMN=TEXT=CLOB' WHERE ASL_SCHEMA_OWNER = 'INTERSPC' AND  ASL_TABLE_NAME = 'ITPRNOTE';
UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_IND_ACTIVE_JN  = 'N', ASL_OPMERKING=ASL_OPMERKING||' COLUMN=TEXT=CLOB' WHERE ASL_SCHEMA_OWNER = 'INTERSPC' AND  ASL_TABLE_NAME = 'REFERENCE_TEXT';
UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_IND_ACTIVE_JN  = 'N', ASL_OPMERKING=ASL_OPMERKING||' COLUMN=TEXT=CLOB' WHERE ASL_SCHEMA_OWNER = 'INTERSPC' AND  ASL_TABLE_NAME = 'SPECIFICATION_TEXT';
--
UPDATE DBA_AWS_SUPPLEMENTAL_LOG SET ASL_IND_ACTIVE_JN  = 'N', ASL_OPMERKING=ASL_OPMERKING||' COLUMN=DESKTOP_OBJECT=BLOB' WHERE ASL_SCHEMA_OWNER = 'INTERSPC' AND  ASL_TABLE_NAME = 'ITOIRAW';
--
SELECT COUNT(*), ASL_IND_ACTIVE_JN FROM DBA_AWS_SUPPLEMENTAL_LOG GROUP BY ASL_IND_ACTIVE_JN;

COMMIT;



--
-- Create ADD-SUPPLEMENTAL-LOGGING PROCEDURE
--
--drop procedure dba_aws_add_supplemental_log;
--create or replace procedure dba_aws_add_supplemental_log (p_table_name varchar2 default null, p_debug varchar2 default 'J')
/*
alter table ATTACHED_SPECIFICATION add supplemental log data (all) columns;
*/

SET SERVEROUTPUT ON
--INCL DEBUG, GEEN COMMIT...
BEGIN DBA_AWS_ADD_SUPPLEMENTAL_LOG (p_table_name=>'HEADER', p_debug=>'J'); END;
--DAADWERKELIJK AANZETTEN...
--BEGIN DBA_AWS_ADD_SUPPLEMENTAL_LOG (p_table_name=>'HEADER', p_debug=>'N'); END;

--alle tabellen in schema...
BEGIN DBA_AWS_ADD_SUPPLEMENTAL_LOG (p_table_name=>'', p_debug=>'J'); END;
--************************************************************************************************************
--************************************************************************************************************
--en nu HELE SCHEMA voor het ECHIE...!!!!!!!!!!!!!!!!!!!! (DEBUG=N)
BEGIN DBA_AWS_ADD_SUPPLEMENTAL_LOG (p_table_name=>'', p_debug=>'N'); END;

--evt. voor specifieke tabel
--BEGIN DBA_AWS_ADD_SUPPLEMENTAL_LOG (p_table_name=>'HEADER', p_debug=>'N'); END;

alter system switch logfile; 
--************************************************************************************************************
--************************************************************************************************************



--******************************************************************
--******************************************************************
--EVT. herstellen van activation-date:
--******************************************************************
--******************************************************************
/*
select table_name from dba_aws_supplemental_log where asl_activation_date is null;

update dba_aws_supplemental_log set asl_activation_date = null where asl_activation_date > trunc(sysdate);
commit;
*/


--CONTROLE TABELLEN MET SUPPLEMENTAL-LOGGING...
--Alles is gebaseerd op de LOG-GROUP. Geef je deze niet expliciet op, dan genereert oracle deze (SYS_%).
--WHERE LOG_GROUP_TYPE='ALL COLUMN LOGGING'
select * from ALL_LOG_GROUPS where  OWNER='INTERSPC' ; 
 --and TABLE_NAME='UTEQ';
/*
INTERSPC	SYS_C0076704	ITLIMSJOB	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076705	ITLIMSTMP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076714	ITPP_DEL	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076749	ITLIMSCONFLY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076710	ITOIH	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076711	ITOIRAW	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076713	ITPLGRPLIST	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076748	USER_GROUP_LIST	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076709	ITOID	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076715	ITPRCL	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076716	ITPRMFC	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076717	ITPRNOTE	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076718	ITSHDEL	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076674	ATFUNCBOM	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076675	ATFUNCBOMDATA	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076676	ATFUNCBOMWORKAREA	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076682	AVARTICLEPRICES	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076746	UOM	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076664	ATTACHED_SPECIFICATION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076671	ACCESS_GROUP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076672	APPROVAL_HISTORY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076673	ASSOCIATION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076677	ATTRIBUTE	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076678	PART	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076683	CHARACTERISTIC	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076684	CHARACTERISTIC_ASSOCIATION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076712	ITPLGRP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076725	PLANT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076736	REF_TEXT_TYPE	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076737	STATUS	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076687	FRAME_KW	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076692	HEADER_H	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076693	ITBOMLY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076694	ITBOMLYITEM	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076695	ITBOMLYSOURCE	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076667	REFERENCE_TEXT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076680	SPECIFICATION_KW	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076735	REASON	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076738	SECTION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076739	SECTION_H	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076742	SUB_SECTION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076743	SUB_SECTION_H	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076744	TEST_METHOD	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076745	TEXT_TYPE	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076665	BOM_HEADER	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076685	CLASS3	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076686	FRAME_HEADER	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076691	HEADER	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076696	ITCLAT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076697	ITCLD	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076700	ITKW	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076703	ITLANG	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076707	ITMFCMPL	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076701	ITKWAS	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076702	ITKWCH	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076706	ITMFC	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076708	ITMPL	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076666	BOM_ITEM	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076669	SPECIFICATION_SECTION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076688	FRAME_PROP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076689	FRAME_SECTION	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076690	FRAME_TEXT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076698	ITCLTV	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076726	PROPERTY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076731	PROPERTY_GROUP_LIST	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076732	PROPERTY_H	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076721	ITUS	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076722	LAYOUT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076727	PROPERTY_DISPLAY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076728	PROPERTY_GROUP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076729	PROPERTY_GROUP_DISPLAY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076730	PROPERTY_GROUP_H	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076734	PROPERTY_TEST_METHOD	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076681	SPECIFICATION_HEADER	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076719	ITSHQ	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076723	MATERIAL_CLASS	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076724	PART_PLANT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076733	PROPERTY_LAYOUT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076740	SPECIFICATION_TEXT	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076741	STATUS_HISTORY	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076668	SPECIFICATION_PROP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076679	SPECDATA	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076699	ITFRMDEL	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076720	ITUP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
INTERSPC	SYS_C0076747	USER_GROUP	ALL COLUMN LOGGING	ALWAYS	GENERATED NAME
*/
select * from ALL_LOG_GROUPS where  OWNER='INTERSPC' ;  --and TABLE_NAME='ITUP';

--group-columns (worden niet aangemaakt als je ze niet opgeeft...)
select * from ALL_LOG_GROUP_COLUMNS where  OWNER='INTERSPC' ;  
--and TABLE_NAME='HEADER' AND COLUMN_NAME='DESCRIPTION';
--no rows selected...

--
--CONTROLE WELKE TABELLEN NIET VAN SUPPLEMENTAL-LOGGING ZIJN VOORZIEN:
--
select asl_table_name from dba_aws_supplemental_log where asl_table_name not in (select log.table_name from dba_log_groups LOG where LOG.owner='INTERSPC' );
/*
SPECIFICAITON_KW         --update dba_aws_supplemental_log  set asl_table_name ='SPECIFICATION_KW'  where asl_table_name='SPECIFICAITON_KW' 
                          --delete from dba_aws_supplemental_log where asl_table_name like 'SPECIFICAITON_KW' 
AVSEPCIFICATION_WEIGHT   --update dba_aws_supplemental_log  set asl_table_name ='AVSPECIFICATION_WEIGHT'  where asl_table_name='AVSPECIFICATION_WEIGHT' 
                         
RVPART_PLANT             --DELETE FROM  dba_aws_supplemental_log where asl_table_name like 'RVPART_PLANT' 
*/




--
--HERSTELLEN / VERWIJDEREN VAN SUPPLEMENTAL-LOGGING
--OP GEHELE DATABASE: ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
--                    ALTER DATABASE DROP SUPPLEMENTAL LOG DATA;
--PER TABEL:   alter table [TABLE_NAME] drop supplemental log group [GROUP_NAME]
--OF:
/*
alter table HEADER drop supplemental log data (all) columns;
--
alter system switch logfile; 
*/


prompt
prompt einde script
prompt

