--WE HEBBEN 168 ACCESS-GROUPS !!!
--WE HEBBEN 95 USER-GROUPS !!!
--

--vantevoren wel eerst een selectie uitvoeren op de USERGROUP-tabel om
--de KOLOM-HEADERS te selecteren, deze komen niet mee, met onderstaande constructie.
select ug.user_group_id||'-'||ug.description
from user_group ug
order by ug.user_group_id
;

--SELECTIE CONTENT
--Per USER(LOOP-RIJ), gaan we per USERGROUP-LOOP(=KOLOM) de gerelateerde ACCESSGROUPS/FRAMES(=CELL) ophalen.
SET SERVEROUTPUT ON
SET LINESIZE 32000
DECLARE
--selectie alle USERS
CURSOR C_USR 
IS
SELECT DISTINCT U.USER_ID
,      U.FORENAME||' '||U.LAST_NAME         USR_NAAM
,      AG.ACCESS_GROUP
,      AG.ACCESS_GROUP||'-'||AG.DESCRIPTION  AG_NAAM
--,      U.PROD_ACCESS
FROM APPLICATION_USER U 
,    USER_GROUP_LIST  UGL
,    USER_GROUP       UG
,    USER_ACCESS_GROUP UAG
,    ACCESS_GROUP     AG
WHERE U.USER_ID = UGL.USER_ID
AND   UGL.USER_GROUP_ID = UG.USER_GROUP_ID
AND   UG.USER_GROUP_ID  = UAG.USER_GROUP_ID
AND   UAG.ACCESS_GROUP  = AG.ACCESS_GROUP
--AND   u.user_id in ('AAF')
ORDER BY U.USER_ID, AG.ACCESS_GROUP
;
--selectie alle UG
CURSOR C_UG 
IS
SELECT U.USER_GROUP_ID
,      U.DESCRIPTION
FROM USER_GROUP U
ORDER BY U.USER_GROUP_ID
;
--selectie alle USER-GROUPS voor USER
CURSOR C_UGL (P_USR  IN VARCHAR2
             ,P_UG  IN NUMBER )
IS 
SELECT UGL.USER_ID
,      UGL.USER_GROUP_ID
FROM USER_GROUP_LIST UGL
WHERE UGL.USER_ID       = P_USR
AND   UGL.USER_GROUP_ID = P_UG
;
--selectie FRAMES binnen AG
CURSOR C_F (P_AG  IN NUMBER )
IS 
SELECT F.FRAME_NO
,      F.DESCRIPTION
FROM FRAME_HEADER F
WHERE F.ACCESS_GROUP = P_AG
and   F.STATUS=2        --current
;
L_AANTAL_FRAMES   NUMBER := 0;
L_STATEMENT_BASE  VARCHAR2(32000);
L_STATEMENT_TOT   VARCHAR2(32000);
BEGIN
  DBMS_OUTPUT.ENABLE(BUFFER_SIZE=>NULL);
  FOR R_USR IN C_USR
  LOOP
    --iedere rij begin met USER
    L_STATEMENT_BASE := R_USR.USER_ID||'-'||R_USR.USR_NAAM||':'||R_USR.AG_NAAM;
	--DBMS_OUTPUT.PUT_LINE(L_STATEMENT_BASE);
	--iedere kolom aparte UG
    FOR R_UG IN C_UG
	LOOP
	  --bouw per KOLOM=USERGROUP de CELL-CONTENT ( ACCESSGROUP/FRAMES) op
	  L_STATEMENT_BASE := L_STATEMENT_BASE||';';
	  --L_STATEMENT_TOT  := L_STATEMENT_BASE;
	  --INDIEN RELATIE-AANWEZIG TUSSEN USER + USERGROUP DAN EXTRA INFO BEPALEN
	  FOR R_UGL IN C_UGL(R_USR.USER_ID, R_UG.USER_GROUP_ID)
	  LOOP
        --per USER/ACCESSGROUP/USERGROUP kijken welke FRAMES voorkomen
		L_AANTAL_FRAMES := 0;
        FOR R_F IN C_F(R_USR.ACCESS_GROUP)
        LOOP
		  L_AANTAL_FRAMES := L_AANTAL_FRAMES + 1;
		  IF L_AANTAL_FRAMES > 1
		  THEN
            --er kunnen meerdere frames per ACCESS-GROUP voorkomen. Ook deze binnen 1 cel opnemen
            L_STATEMENT_BASE := L_STATEMENT_BASE||'#'||R_F.FRAME_NO;
		  ELSE
            L_STATEMENT_BASE := L_STATEMENT_BASE||R_F.FRAME_NO;
		  END IF;
        END LOOP; --C-F
        --
	    --
	  END LOOP;  --C_UGL
	  --
	END LOOP;  --C_UG
	--
	L_STATEMENT_BASE := L_STATEMENT_BASE ;
	DBMS_OUTPUT.PUT_LINE(L_STATEMENT_BASE);
  END LOOP;  --C_USR
END;
/


PROMPT LET OP: LINESIZE IS NIET GROOT GENOEG VANUIT SQL*DEVELOPER.
PROMPT         DE OUTPUT-FILE DUS HANDMATIG VOOR EEN PAAR GEBRUIKERS MET EEN HELEBOEL USERGROUPS EVEN HANDMATIG IN 
PROMPT         NOTEPAD++ WEER OP 1 REGEL ZETTEN VOORDAT JE BESTAND IN EXCEL INLEEST. 
PROMPT

prompt einde script




