--WE HEBBEN 168 ACCESS-GROUPS !!!
--WE HEBBEN 95 USER-GROUPS !!!
--
select ug.user_group_id||'-'||ug.description
from user_group ug
order by ug.user_group_id
;


--selectie inhoud spreadsheet...

SET SERVEROUTPUT ON
DECLARE
CURSOR C_AG IS
SELECT A.ACCESS_GROUP
,      A.DESCRIPTION
FROM ACCESS_GROUP A 
ORDER BY A.ACCESS_GROUP
;
CURSOR C_UG IS
SELECT U.USER_GROUP_ID
,      U.DESCRIPTION
FROM USER_GROUP U
ORDER BY U.USER_GROUP_ID
;
CURSOR C_AUG (P_AG  IN NUMBER
             ,P_UG  IN NUMBER )
IS SELECT UAG.UPDATE_ALLOWED			 
FROM USER_ACCESS_GROUP UAG
WHERE UAG.ACCESS_GROUP = P_AG
AND   UAG.USER_GROUP_ID = P_UG
;
L_STATEMENT VARCHAR2(4000);
BEGIN
  FOR R_AG IN C_AG 
  LOOP
    L_STATEMENT := R_AG.ACCESS_GROUP||'-'||R_AG.DESCRIPTION;
    FOR R_UG IN C_UG
	LOOP
	  L_STATEMENT := L_STATEMENT||';';
	  FOR R_UAG IN C_AUG(R_AG.ACCESS_GROUP, R_UG.USER_GROUP_ID)
	  LOOP
	    L_STATEMENT := L_STATEMENT||R_UAG.UPDATE_ALLOWED;
	  END LOOP;
	END LOOP;  --C_UG
	--
	DBMS_OUTPUT.PUT_LINE(L_STATEMENT);
  END LOOP;  --C_AG
END;
/






