--WE HEBBEN 168 ACCESS-GROUPS !!!
--WE HEBBEN 95 USER-GROUPS !!!
--


select ug.user_group_id||'-'||ug.description
from user_group ug
order by ug.user_group_id
;


--SELECTIE INHOUD SPREADSHEET

SET SERVEROUTPUT ON
DECLARE
CURSOR C_USR IS
SELECT U.USER_ID
,      U.FORENAME||' '||U.LAST_NAME  NAAM
,      U.PROD_ACCESS
FROM APPLICATION_USER U 
ORDER BY U.USER_ID
;
CURSOR C_UG IS
SELECT U.USER_GROUP_ID
,      U.DESCRIPTION
FROM USER_GROUP U
ORDER BY U.USER_GROUP_ID
;
CURSOR C_UGL (P_USR  IN VARCHAR2
             ,P_UG  IN NUMBER )
IS SELECT *
FROM USER_GROUP_LIST UGL
WHERE UGL.USER_ID       = P_USR
AND   UGL.USER_GROUP_ID = P_UG
;
L_STATEMENT VARCHAR2(4000);
BEGIN
  FOR R_USR IN C_USR
  LOOP
    L_STATEMENT := R_USR.USER_ID||'-'||R_USR.NAAM;
    FOR R_UG IN C_UG
	LOOP
	  L_STATEMENT := L_STATEMENT||';';
	  FOR R_UGL IN C_UGL(R_USR.USER_ID, R_UG.USER_GROUP_ID)
	  LOOP
	    L_STATEMENT := L_STATEMENT||R_USR.PROD_ACCESS;
	  END LOOP;
	END LOOP;  --C_UG
	--
	DBMS_OUTPUT.PUT_LINE(L_STATEMENT);
  END LOOP;  --C_AG
END;
/






