--------------------------------------------------------
--  File created - donderdag-oktober-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATOUTDOOREVENTS
--------------------------------------------------------

  CREATE TABLE "UNILAB"."ATOUTDOOREVENTS" 
   (	"EVENT_NUM" NUMBER, 
	"EVENT_TYPE" VARCHAR2(20 CHAR), 
	"OBJ_TP" VARCHAR2(20 CHAR), 
	"OBJ_ID" VARCHAR2(200 CHAR), 
	"MODIFY_REASON" VARCHAR2(255 CHAR), 
	"HANDLED_ON" TIMESTAMP (6), 
	"HANDLING_ERRCODE" NUMBER, 
	"CREATED_ON" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UNI_DATAC" ;
--------------------------------------------------------
--  DDL for Index SYS_C0069953
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNILAB"."SYS_C0069953" ON "UNILAB"."ATOUTDOOREVENTS" ("EVENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UNI_DATAC" ;
--------------------------------------------------------
--  Constraints for Table ATOUTDOOREVENTS
--------------------------------------------------------

  ALTER TABLE "UNILAB"."ATOUTDOOREVENTS" MODIFY ("EVENT_NUM" NOT NULL ENABLE);
  ALTER TABLE "UNILAB"."ATOUTDOOREVENTS" ADD PRIMARY KEY ("EVENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UNI_DATAC"  ENABLE;
