CREATE TABLESPACE SPECD
DATAFILE 
  'D:\DATABASE\IS61\DATA\IS61_SPECD1.DBF' SIZE 18000M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;




CREATE TABLESPACE SPECI
DATAFILE 
  'D:\DATABASE\IS61\DATA\IS61_SPECI1.DBF' SIZE 33554416K AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED,
  'D:\DATABASE\IS61\DATA\IS61_SPECI2.DBF' SIZE 33554416K AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED,
  'D:\DATABASE\IS61\DATA\IS61_SPECI3.DBF' SIZE 33554416K AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED,
  'D:\DATABASE\IS61\DATA\IS61_SPECI4.DBF' SIZE 33554416K AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;