/*
table: CLICSECID:
--
SERIAL_ID     NOT NULL RAW(160 BYTE)  
SHORTNAME     NOT NULL RAW(160 BYTE)  
SETTING_SEQ   NOT NULL RAW(16 BYTE)   
SETTING_NAME  NOT NULL RAW(160 BYTE)  
SETTING_VALUE          RAW(1024 BYTE) 
*/

CREATE OR REPLACE VIEW AV_BHR_LIC_CLICSECID
(SERIAL_ID      
,SHORTNAME     
,SETTING_SEQ   
,SETTING_NAME  
,SETTING_VALUE 
)
as
SELECT DBA_DECRYPT(SERIAL_ID)
,DBA_DECRYPT(SHORTNAME     )
,DBA_DECRYPT(SETTING_SEQ   )
,DBA_DECRYPT(SETTING_NAME  )
,decode(SETTING_VALUE,'',null,DBA_DECRYPT(SETTING_VALUE))
from  CTLICSECID
;

--where setting_value is null
--union
--SELECT DBA_DECRYPT(SERIAL_ID)
--,DBA_DECRYPT(SHORTNAME     )
--,DBA_DECRYPT(SETTING_SEQ   )
--,DBA_DECRYPT(SETTING_NAME  )
--,DBA_DECRYPT(SETTING_VALUE ) 
--from  CTLICSECID
--where setting_value is not null
--;

/*
TABLE: CTLICSECIDAUXILIARY
--
Name             Null?    Type           
---------------- -------- -------------- 
SERIAL_ID        NOT NULL RAW(160 BYTE)  
SHORTNAME        NOT NULL RAW(160 BYTE)  
HASH_CODE_CLIENT          RAW(1024 BYTE) 
HASH_CODE_SERVER          RAW(1024 BYTE) 
TEMPLATE                  BLOB           
REF_DATE                  RAW(64 BYTE)   
EXPIRATION_DATE           RAW(64 BYTE)
*/

CREATE OR REPLACE VIEW AV_BHR_LIC_CTLICSECIDAUXILIARY
(SERIAL_ID    
,SHORTNAME     
,HASH_CODE_CLIENT
,HASH_CODE_SERVER
--,TEMPLATE        
,REF_DATE        
,EXPIRATION_DATE
)
as
SELECT DBA_DECRYPT(SERIAL_ID)
,  DBA_DECRYPT(SHORTNAME)     
,  DECODE(HASH_CODE_CLIENT,'' ,NULL,DBA_DECRYPT(HASH_CODE_CLIENT))
,  DECODE(HASH_CODE_SERVER,'',NULL,dBA_DECRYPT(HASH_CODE_SERVER))
--,  DECODE(TEMPLATE,'',NULL,DBA_DECRYPT(TEMPLATE) )
,  DECODE(REF_DATE,'',NULL,DBA_DECRYPT(REF_DATE) )
,  DECODE(EXPIRATION_DATE,'',NULL,DBA_DECRYPT(EXPIRATION_DATE))
from  CTLICSECIDAUXILIARY
WHERE length(serial_id) > 8
;

