--view van ITLIMSJOB die nog niet verwerkt zijn:

/*
DESCR ITLIMSJOB
--
Name               Null     Type              
------------------ -------- ----------------- 
PLANT              NOT NULL VARCHAR2(8 CHAR)  
PART_NO            NOT NULL VARCHAR2(18 CHAR) 
REVISION           NOT NULL NUMBER(4)         
DATE_READY                  DATE              
DATE_PROCEED                DATE              
RESULT_PROCEED              NUMBER(1)         
DATE_TRANSFERRED            DATE              
RESULT_TRANSFER             NUMBER(1)         
TO_BE_TRANSFERRED           CHAR(1 CHAR)      
DATE_LAST_UPDATED           DATE              
RESULT_LAST_UPDATE          NUMBER(1)         
TO_BE_UPDATED               CHAR(1 CHAR)      
OBSOLETE_UPDATED            CHAR(1 CHAR)      
ATTACHED_PART_NO            VARCHAR2(18 CHAR) 
PRIORITY                    NUMBER(9)         
*/


CREATE OR REPLACE VIEW AV_DBA_MONITOR_LIMSJOB_ACTIVE
(PLANT
,PART_NO
,REVISION
,DATE_READY
,DATE_PROCEED
,RESULT_PROCEED
,RESULT_TRANSFER
,TO_BE_TRANSFERRED
,RESULT_LAST_UPDATE
,TO_BE_UPDATED
,PRIORITY
,HERSTEL_ACTIE
)
AS
SELECT DISTINCT JOB.PLANT
,JOB.PART_NO
,JOB.REVISION
,JOB.DATE_READY
,JOB.DATE_PROCEED
,JOB.RESULT_PROCEED
,JOB.RESULT_TRANSFER
,JOB.TO_BE_TRANSFERRED
,JOB.RESULT_LAST_UPDATE
,JOB.TO_BE_UPDATED
,JOB.PRIORITY
,'UITZET-CMD: UPDATE ITLIMSJOB SET RESULT_PROCEED=1, TO_BE_UPDATED=DECODE(TO_BE_UPDATED,2,1,TO_BE_UPDATED), TO_BE_TRANSFERED=DECODE(TO_BE_TRANSFERED,2,1,TO_BE_TRANSFERRED) WHERE PLANT='||''''||JOB.PLANT||''''||' AND PART_NO='||''''||JOB.PART_NO||''''||' AND REVISION='||JOB.REVISION||' AND RESULT_PROCEED<>1;'
FROM  ITLIMSJOB JOB
WHERE (  (   JOB.TO_BE_UPDATED = '2' 
         OR  (   JOB.TO_BE_UPDATED <> '0' 
		     AND JOB.RESULT_LAST_UPDATE <> '1' )
		 )
      OR (    JOB.TO_BE_TRANSFERRED = '2' 
         OR  (   JOB.TO_BE_TRANSFERRED <> '0'
		     AND JOB.RESULT_TRANSFER <> '1' )
         )	
	  )
AND nvl(JOB.RESULT_PROCEED,0) <> 1
;

PROMPT 
PROMPT EINDE SCRIPT
PROMPT



