--------------------------------------------------------
--  File created - dinsdag-september-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View WF_SPECIFICATION_HEADER
--------------------------------------------------------

CREATE USER AWSDWH
  IDENTIFIED BY "AVawsDWH_2021"
  DEFAULT TABLESPACE UNI_DATAO
  TEMPORARY TABLESPACE UNI_TEMP
  QUOTA UNLIMITED ON UNI_DATAO
  ACCOUNT UNLOCK;

--productie-omgeving
ALTER USER AWSDWH IDENTIFIED BY "AVawsDWH_2021P" ;


-- 2 Roles for AWSDWH
GRANT CONNECT TO AWSDWH;
--GRANT DEV_MGR TO AWSDWH;
--GRANT LIMITED TO AWSDWH;
GRANT CREATE SESSION TO AWSDWH;
GRANT SELECT ANY TABLE TO AWSDWH;
GRANT SELECT ANY DICTIONARY TO AWSDWH;


--GRANT GRANT ANY PRIVILEGE TO INTERSPC;
--GRANT SELECT ANY DICTIONARY TO INTERSPC;
--GRANT UNLIMITED TABLESPACE TO INTERSPC;

--conn system
GRANT CREATE SESSION TO AWSDWH;
GRANT SELECT ANY TRANSACTION TO AWSDWH;
GRANT SELECT ON V_$ARCHIVED_LOG TO AWSDWH;
GRANT SELECT ON V_$LOG TO AWSDWH;
GRANT SELECT ON V_$LOGFILE TO AWSDWH;
GRANT SELECT ON V_$LOGMNR_LOGS TO AWSDWH;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO AWSDWH;
GRANT SELECT ON V_$DATABASE TO AWSDWH;
GRANT SELECT ON V_$THREAD TO AWSDWH;
GRANT SELECT ON V_$PARAMETER TO AWSDWH;
GRANT SELECT ON V_$NLS_PARAMETERS TO AWSDWH;
GRANT SELECT ON V_$TIMEZONE_NAMES TO AWSDWH;
GRANT SELECT ON V_$TRANSACTION TO AWSDWH;
GRANT SELECT ON ALL_INDEXES TO AWSDWH;
GRANT SELECT ON ALL_OBJECTS TO AWSDWH;
GRANT SELECT ON ALL_TABLES TO AWSDWH;
GRANT SELECT ON ALL_USERS TO AWSDWH;
GRANT SELECT ON ALL_CATALOG TO AWSDWH;
GRANT SELECT ON ALL_CONSTRAINTS TO AWSDWH;
GRANT SELECT ON ALL_CONS_COLUMNS TO AWSDWH;
GRANT SELECT ON ALL_TAB_COLS TO AWSDWH;
GRANT SELECT ON ALL_IND_COLUMNS TO AWSDWH;
GRANT SELECT ON ALL_LOG_GROUPS TO AWSDWH;
GRANT SELECT ON ALL_TAB_PARTITIONS TO AWSDWH;
--GRANT SELECT ON V_$CONTAINERS TO AWSDWH;        --table doesn't exist !!! =ORACLE19.PDB             


--CONN SYS
GRANT SELECT ON ALL_ENCRYPTED_COLUMNS TO AWSDWH;    --ORA-01031: insufficient privileges
GRANT SELECT ON SYS.DBA_REGISTRY TO AWSDWH;         --ORA-01031. 00000 -  "insufficient privileges"
GRANT SELECT ON SYS.OBJ$ TO AWSDWH;                 --ORA-01031: insufficient privileges
GRANT SELECT ON DBA_TABLESPACES TO AWSDWH;          --01031. 00000 -  "insufficient privileges"


/*
--UITDELEN VAN SPECIFIEKE GRANTS OP TABELLEN...

SET SERVEROUTPUT ON
DECLARE
l_stmnt varchar2(4000);
BEGIN
FOR x IN (SELECT ASL_TABLE_NAME  FROM DBA_AWS_SUPPLEMENTAL_LOG order by asl_table_name )
  LOOP   
    l_stmnt := 'GRANT SELECT ON ' || x.asl_table_name || ' TO AWSDWH ';
	dbms_output.put_line(l_stmnt);
    EXECUTE IMMEDIATE l_stmnt; 
  END LOOP; 
END;
/

*/



