ALTER USER INTERSPC  IDENTIFIED BY "stardust2021av" ;
ALTER USER UNILAB  IDENTIFIED BY "stardust2021av" ;


--db-links VANUIT INTERSPEC naar UNILAB:
--automatisch aangemaakt vanuit PA_DBLINK
CREATE DATABASE LINK "LNK_LIMS_H.REGRESS.RDBMS.DEV.US.ORACLE.COM"    CONNECT TO "LIMS" IDENTIFIED BY  'l1ms'   USING 'U611';
CREATE DATABASE LINK "LNK_LIMS.REGRESS.RDBMS.DEV.US.ORACLE.COM"    CONNECT TO "LIMS" IDENTIFIED BY  'l1ms'    USING 'U611';  
--handmatig:
drop database link "U611.REGRESS.RDBMS.DEV.US.ORACLE.COM";
CREATE DATABASE LINK "U611.REGRESS.RDBMS.DEV.US.ORACLE.COM"   CONNECT TO "UNILAB" IDENTIFIED BY  'moonflower'    USING 'U611';
CREATE DATABASE LINK "U611.REGRESS.RDBMS.DEV.US.ORACLE.COM"   CONNECT TO "UNILAB" IDENTIFIED BY  'stardust2021'    USING 'U611';



--db-links vanuit UNILAB naar INTERSPEC:
--handmatig
DROP PUBLIC DATABASE LINK "INTERSPEC";
CREATE PUBLIC DATABASE LINK "INTERSPEC"   CONNECT TO "INTERSPC" IDENTIFIED BY  "moonflower"   USING 'IS61';
CREATE PUBLIC DATABASE LINK "INTERSPEC"   CONNECT TO "INTERSPC" IDENTIFIED BY  "stardust2021av"   USING 'IS61';
--handmatig
DROP PUBLIC DATABASE LINK   "INTERSPEC.REGRESS.RDBMS.DEV.US.ORACLE.COM";
CREATE PUBLIC DATABASE LINK "INTERSPEC.REGRESS.RDBMS.DEV.US.ORACLE.COM"   CONNECT TO "INTERSPC" IDENTIFIED BY  "moonflower"   USING 'IS61';
CREATE PUBLIC DATABASE LINK "INTERSPEC.REGRESS.RDBMS.DEV.US.ORACLE.COM"   CONNECT TO "INTERSPC" IDENTIFIED BY  "stardust2021av"   USING 'IS61';






PROMPT EINDE SCRIPT



