select table_name from all_tab_columns where table_name like 'UT%' AND COLUMN_NAME='HIDDEN';
--
select COUNT(*) from utuptkdetails WHERE HIDDEN=1;
select COUNT(*) from utupUStkdetails WHERE HIDDEN=1;
select COUNT(*) from uttk where tk_tp='melist' AND HIDDEN=1;
select COUNT(*) from utmtcell where hidden=1;
select COUNT(*) from UTSCIC where hidden=1;
select COUNT(*) from UTSCII where hidden=1;
select COUNT(*) from UTSCMECELL where hidden=1;
select COUNT(*) from UTRTIP where hidden=1;
select COUNT(*) from UTPTIP where hidden=1;
select COUNT(*) from UTRQIC where hidden=1;
select COUNT(*) from UTRQII where hidden=1;
select COUNT(*) from UTRSCMECELL where hidden=1;
select COUNT(*) from UTSTIP where hidden=1;
select COUNT(*) from UTIE where hidden=1;
select COUNT(*) from UTSDIC where hidden=1;
select COUNT(*) from UTSDII where hidden=1;
select COUNT(*) from UTIP where hidden=1;
select COUNT(*) from UTIPIE where hidden=1;
select COUNT(*) from UTMELSSAVESCMECELL where hidden=1;
select COUNT(*) from UTSTIPBUFFER where hidden=1;


utuptkdetails		0
utupUStkdetails		0
uttk				14
utmtcell			11605
UTSCIC				0
UTSCII				86406
UTSCMECELL			523949
UTRTIP				1
UTPTIP				0
UTRQIC				2
UTRQII				42
UTRSCMECELL			6177
UTSTIP				0
UTIE				1
UTSDIC				0
UTSDII				0
UTIP				0
UTIPIE				18
UTMELSSAVESCMECELL	0
UTSTIPBUFFER		0

--ALLE TABELLEN MET ATTRIBUUT=HIDDEN hebben ook attribuut=IS_PROTECTED.
--Er is aparte groep tabellen die alleen attribuut IS_PROTECTED hebben.

select 'SELECT '||''''||tab.table_name||''''||', COUNT(*), SUM(IS_PROTECTED) FROM '||tab.table_name
from all_tables tab where tab.table_name like 'UT%' 
and exists (select '' from all_tab_columns col where col.table_name = tab.table_name AND COLUMN_NAME='IS_PROTECTED' )
and NOT exists (select '' from all_tab_columns col where col.table_name = tab.table_name AND COLUMN_NAME='HIDDEN' )
order by tab.table_name;
/*
SELECT 'UTAU', COUNT(*), SUM(IS_PROTECTED) FROM UTAU 
UNION
SELECT 'UTAU_20090318', COUNT(*), SUM(IS_PROTECTED) FROM UTAU_20090318 
UNION
SELECT 'UTAU_20090408COMBI', COUNT(*), SUM(IS_PROTECTED) FROM UTAU_20090408COMBI 
UNION
SELECT 'UTAU_20090408PROD', COUNT(*), SUM(IS_PROTECTED) FROM UTAU_20090408PROD 
UNION
SELECT 'UTGKCH', COUNT(*), SUM(IS_PROTECTED) FROM UTGKCH 
UNION
SELECT 'UTGKDC', COUNT(*), SUM(IS_PROTECTED) FROM UTGKDC 
UNION
SELECT 'UTGKME', COUNT(*), SUM(IS_PROTECTED) FROM UTGKME 
UNION
SELECT 'UTGKPT', COUNT(*), SUM(IS_PROTECTED) FROM UTGKPT  
UNION
SELECT 'UTGKRQ', COUNT(*), SUM(IS_PROTECTED) FROM UTGKRQ  
UNION
SELECT 'UTGKRT', COUNT(*), SUM(IS_PROTECTED) FROM UTGKRT  
UNION
SELECT 'UTGKSC', COUNT(*), SUM(IS_PROTECTED) FROM UTGKSC  
UNION
SELECT 'UTGKSD', COUNT(*), SUM(IS_PROTECTED) FROM UTGKSD  
UNION
SELECT 'UTGKST', COUNT(*), SUM(IS_PROTECTED) FROM UTGKST  
UNION
SELECT 'UTGKWS', COUNT(*), SUM(IS_PROTECTED) FROM UTGKWS   
*/
/*
UTAU	784	250
UTGKCH	0	
UTGKDC	0	
UTGKME	30	12
UTGKPT	0	
UTGKRQ	25	6
UTGKRT	9	0
UTGKSC	44	23
UTGKSD	0	
UTGKST	49	2
UTGKWS	35	3
*/


select 'SELECT '||''''||tab.table_name||''''||', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM '||tab.table_name
from all_tables tab where tab.table_name like 'UT%' 
and exists (select '' from all_tab_columns col where col.table_name = tab.table_name AND COLUMN_NAME='IS_PROTECTED' )
and exists (select '' from all_tab_columns col where col.table_name = tab.table_name AND COLUMN_NAME='HIDDEN' )
order by tab.table_name;

/*
SELECT 'UTIE', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTIE
UNION 
SELECT 'UTIP', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTIP
UNION 
SELECT 'UTIPIE', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTIPIE
UNION 
SELECT 'UTMELSSAVESCMECELL', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTMELSSAVESCMECELL
UNION 
SELECT 'UTMTCELL', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTMTCELL
UNION 
SELECT 'UTPTIP', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTPTIP
UNION 
SELECT 'UTRQIC', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTRQIC
UNION 
SELECT 'UTRQII', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTRQII
UNION 
SELECT 'UTRSCMECELL', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTRSCMECELL
UNION 
SELECT 'UTRTIP', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTRTIP
UNION 
SELECT 'UTSCIC', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSCIC
UNION 
SELECT 'UTSCII', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSCII
UNION 
SELECT 'UTSCMECELL', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSCMECELL
UNION 
SELECT 'UTSDIC', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSDIC
UNION 
SELECT 'UTSDII', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSDII
UNION 
SELECT 'UTSTIP', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSTIP
UNION 
SELECT 'UTSTIPBUFFER', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTSTIPBUFFER
UNION 
SELECT 'UTTK', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTTK
UNION 
SELECT 'UTUPTKDETAILS', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTUPTKDETAILS
UNION 
SELECT 'UTUPUSTKDETAILS', COUNT(*), SUM(IS_PROTECTED), SUM(HIDDEN) FROM UTUPUSTKDETAILS
*/

/*
TABELLEN			COUNT		PROTECTED	HIDDEN
UTIE				873			51			1
UTIP				416			1			0
UTIPIE				2873		5550		5658
UTMELSSAVESCMECELL	0		
UTMTCELL			257458		119392		11605
UTPTIP				0		
UTRQIC				135675		0			2
UTRQII				639179		78726		42
UTRSCMECELL			308139		116618		6177
UTRTIP				1310		0			1
UTSCIC				3886582		0			0
UTSCII				16887027	1631894		86406
UTSCMECELL			22578440	11060350	523949
UTSDIC				0		
UTSDII				0		
UTSTIP				77147		0			0
UTSTIPBUFFER		0		
UTTK				631			16			30
UTUPTKDETAILS		3			0			0
UTUPUSTKDETAILS		0		
*/

--CONCLUSIE: OP TK-LEVEL ZIJN ER WEL TAKEN MET PROTECTED-VALUES. Maar deze komen niet terug in relatie met UP/US !!!!
--           DEZE ATTRIBUTEN WORDEN DUS NIET GEBRUIKTS VOOR HET AUTORISEREN/AANZETTEN VAN DE SAVE-LAYOUT-OPTION IN SAMPLE-RESULTS
--           PARAMETER/METHODES-SCHERM.
--







select table_name from all_tab_columns where table_name like 'UT%' AND COLUMN_NAME LIKE '%PROTECTED';

SELECT A.UP, A.TK_TP, A.TK, B.SEQ, B.COL_ID, B.COL_TP,
          A.DEF_VAL, A.HIDDEN, A.IS_PROTECTED, A.MANDATORY,
          A.AUTO_REFRESH, A.COL_ASC, B.VALUE_LIST_TP, A.DSP_LEN, A.INHERIT_TK
   FROM UTUPTKDETAILS A, UTTK B
   WHERE A.VERSION = NVL(null A.VERSION)
     AND A.UP = NVL(null, A.UP) 
     AND A.TK_TP LIKE 'melist'
     --AND A.TK LIKE 'avDef'
     AND A.TK_TP = B.TK_TP
     AND A.TK = B.TK
     AND A.COL_ID = B.COL_ID
     AND A.COL_TP = B.COL_TP
   UNION
   SELECT A.UP, B.TK_TP, B.TK, B.SEQ, B.COL_ID, B.COL_TP,
          B.DEF_VAL, B.HIDDEN, B.IS_PROTECTED, B.MANDATORY,
          B.AUTO_REFRESH, B.COL_ASC, B.VALUE_LIST_TP, B.DSP_LEN, '1'
   FROM UTUPTK A, UTTK B
   WHERE (B.TK_TP, B.TK, B.COL_ID, B.COL_TP) NOT IN 
      (SELECT TK_TP, TK, COL_ID, COL_TP
       FROM UTUPTKDETAILS
       WHERE VERSION = A.VERSION
         AND UP = A.UP
         AND TK_TP LIKE L_TK_TP_IN
         AND TK LIKE L_TK_IN)
     AND A.VERSION = NVL(A_VERSION_IN, A.VERSION)
     AND A.UP = NVL(A_UP_IN, A.UP)
     AND A.TK_TP LIKE L_TK_TP_IN
     AND A.TK LIKE L_TK_IN
     AND A.TK_TP = B.TK_TP
     AND A.TK = B.TK
   ORDER BY 1,2,4;